### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by ghost** [smartgravity/grav-theme-bones-vanilla#2]
Very nice theme. I would like to use SASS. Do you have plans incorporating it?

**Comment by benblee** [comment]
I have this theme with all SCSS files and this theme was created from those being compiled. I'm working on setting up a theme with all the SCSS files and the JS separated as well. Hoping to have it out end of this week.

The idea is to allow you to download Foundation however you want, then just have a couple files for you to add/override to run the theme. The main theme with all options will be called "Bones". This one is "Bones Vanilla" since it's only the CSS and JS.

**Comment by ghost** [comment]
Thanks for the work, this is what I am looking for. I usually use Drupal with Foundation, now switching to Grav. Good to be able to use latest version of Foundation.

**Comment by benblee** [comment]
I've got the first version of the SCSS theme posted now. I've still got a few tweaks to make, but it should work fine with this theme's skeleton. 

If you use the Admin Plugin for Grav, I've added toggles for all Foundation Javascript items so you only need to include what you're using. You can also override this at the page level if you want some features on some pages but not all. It's easiest to see from the Admin Plugin now since I don't have it documented yet.

https://github.com/smartgravity/grav-theme-bones

I have a few thoughts, like moving all javascript out of the **/bower** directory and into the **/js** but I like that right now, things line up with a standard Foundation6 download.

All thoughts and critiques are welcome!

**Comment by ghost** [comment]
Sounds like heaven :-)
Will use it for a few projects and let you know.

**Comment by benblee** [comment]
Much more caught up with what I wanted to add for **Foundation** options.

The theme now has options for what JS and CSS you want to include. All SCSS files are included and there is a CodeKit config file included, so it should work right out of the box if you're using CodeKit. Grav's "pipeline" feature will combine and compress all CSS for production, so I was able to split it up this way for development. The same with the JS.

Still some issues, but the ones I've noticed are noted on the theme repo.
https://github.com/smartgravity/grav-theme-bones
(issues noticed so far here)
https://github.com/smartgravity/grav-theme-bones/issues

Here's the full skeleton Grav install with sample data:
https://github.com/smartgravity/grav-skeleton-bones-site
(zip downloads in the **Releases** section)
https://github.com/smartgravity/grav-skeleton-bones-site/releases

After I get a few more things sorted, I'll submit the theme to the Grav site, so it should be official soon.

I'm going to close this issue now, but feel free to open others with questions and bug reports!

Thanks for the interest!
